//CATEGORY ACTION
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const ADD_QUESTION = 'ADD_QUESTION'

//FILTER ACTION
export const SET_TEXT_FITLER = 'SET_TEXT_FILTER'
export const SET_LEVEL_FILTER = 'SET_LEVEL_FILTER'
